/** [deck, question, answer, why] */
export const FLASH_MANUAL: [string, string, string, string][] = [
  ["Complexity", "Time to access arr[i]?", "O(1)", "The address is computed directly from the index."],
  ["Complexity", "Time for arr.shift() or arr.unshift(x) in JS?", "O(n)", "Every remaining element is re-indexed."],
  ["Complexity", "Map.get / Set.has average time?", "O(1)", "Hashing jumps straight to the bucket."],
  ["Complexity", "Binary search time?", "O(log n)", "Each step halves the remaining range."],
  ["Complexity", "Time of Array.prototype.sort?", "O(n log n)", "JS engines use TimSort / merge-based sorts."],
  ["Complexity", "Space used by recursion n levels deep?", "O(n)", "Each call keeps a stack frame until it returns."],
  ["Complexity", "Naive recursive Fibonacci time?", "O(2ⁿ)", "Each call branches twice; memoization makes it O(n)."],
  ["Complexity", "Number of subsets of n items?", "2ⁿ", "Each item is either in or out."],
  ["Complexity", "Number of permutations of n distinct items?", "n!", "n choices for the first, n-1 for the second…"],
  ["Complexity", "Why is a monotonic stack pass O(n) despite a while loop inside a for loop?", "Each element is pushed once and popped at most once", "Total pops across the whole run ≤ n."],
  ["Complexity", "Inserting into a balanced BST?", "O(log n)", "Height is log n; skewed trees degrade to O(n)."],
  ["Complexity", "Reading the k-th node of a linked list?", "O(k)", "No random access: you walk from head."],
  ["Pattern", "\"Longest substring without repeating characters\" → ?", "Sliding Window + Map", "Contiguous + longest + condition on characters."],
  ["Pattern", "\"Sorted array, find two numbers that sum to target\" → ?", "Two Pointers", "Move left if sum too small, right if too big."],
  ["Pattern", "\"Subarray sum equals k\" with negative numbers → ?", "Prefix Sum + Map", "Sliding window breaks with negatives."],
  ["Pattern", "\"Next greater element\" → ?", "Monotonic Stack", "Pop smaller elements when a bigger one arrives."],
  ["Pattern", "\"Top K frequent elements\" → ?", "Heap or bucket sort", "Keep the best k; or bucket by frequency."],
  ["Pattern", "\"All subsets / permutations\" → ?", "Backtracking", "Choose, recurse, undo."],
  ["Pattern", "\"Shortest path in an unweighted grid\" → ?", "BFS", "First time you reach a cell is the shortest distance."],
  ["Pattern", "\"Detect a cycle in a linked list\" → ?", "Fast & Slow Pointers", "The fast pointer laps the slow one inside a cycle."],
  ["Pattern", "\"Minimum speed / capacity such that…\" → ?", "Binary Search on the answer", "Feasibility is monotonic."],
  ["Pattern", "\"Merge overlapping intervals\" → ?", "Sort by start, then merge", "Compare with the last merged interval only."],
  ["Pattern", "\"Number of ways to…\" / min cost with choices → ?", "Dynamic Programming", "Overlapping subproblems + optimal substructure."],
  ["Pattern", "\"Count islands in a grid\" → ?", "DFS / BFS flood fill", "Each new unvisited land cell starts a new island."],
  ["Concept", "What makes a problem suitable for binary search?", "A sorted order or a monotonic yes/no condition", "You must be able to discard half safely."],
  ["Concept", "LIFO vs FIFO?", "Stack = Last In First Out; Queue = First In First Out", "Stack: plates. Queue: ticket line."],
  ["Concept", "What does inorder traversal of a BST give?", "Values in sorted order", "Left < node < right, visited L → N → R."],
  ["Concept", "Two parts every recursive function needs?", "Base case + recursive case moving toward it", "Without a base case you get a stack overflow."],
  ["Concept", "Why use a dummy node in linked list problems?", "So the head is never a special case", "Return dummy.next at the end."],
  ["Concept", "What does a hash map trade?", "Memory for speed", "O(n) extra space to get O(1) lookups."],
  ["Algorithm", "Binary search: when arr[mid] < target, what do you do?", "left = mid + 1", "mid is already ruled out, so skip it."],
  ["Algorithm", "Kadane's update rule?", "cur = max(x, cur + x); best = max(best, cur)", "Restart when the running sum hurts."],
  ["Algorithm", "Reverse a linked list: the 4 lines in the loop?", "next = cur.next; cur.next = prev; prev = cur; cur = next", "Save, flip, advance, advance."],
  ["Algorithm", "Sliding window length formula?", "right - left + 1", "Both ends are inclusive."],
  ["Algorithm", "BFS: when do you mark a node visited?", "When you enqueue it", "Marking on dequeue lets duplicates into the queue."],
  ["Algorithm", "Prefix sum: sum of a[l..r]?", "pre[r + 1] - pre[l]", "With pre[0] = 0."],
  ["Interview trap", "[10, 9, 1].sort() in JS returns?", "[1, 10, 9]", "Default sort compares as strings. Use (a, b) => a - b."],
  ["Interview trap", "Is arr.includes(x) inside a loop O(n)?", "No: O(n²) total", "includes is itself O(n)."],
  ["Interview trap", "Map key [1, 2] then map.get([1, 2])?", "undefined", "Arrays compare by reference. Use a string key like \"1,2\"."],
  ["Interview trap", "Array(3).fill([]) then push to one inner array?", "All three change", "fill shares the same array. Use Array.from({length: 3}, () => [])."],
  ["Interview trap", "Validate BST by comparing each node only with its children?", "Wrong", "A deeper node can violate an ancestor. Pass min/max bounds."],
  ["Interview trap", "typeof null?", "\"object\"", "Historical JS bug. Check node === null explicitly."],
  ["Interview trap", "7 / 2 in JS?", "3.5", "No integer division. Use Math.floor or Math.trunc."],
  ["Interview trap", "Sliding window on sums with negative numbers?", "Doesn't work", "Shrinking may not reduce the sum. Use prefix sums."]
];
