import type { JudgeSpec } from "@/lib/types";

// ===== Judge specs: function signature + test cases per problem. Expected outputs are computed at build time from the reference solutions. =====
// params: [name, type]. Types: number, number[], number[][], string, string[], character[][], ListNode, TreeNode, cycle (ListNode + pos)
// cmp: "unordered" (any order), "groups" (order-free lists of order-free lists), "outer" (order-free list of ordered lists), "float"
export const JUDGE: Record<string, JudgeSpec> = {
  "two-sum": { fn: "twoSum", params: [["nums", "number[]"], ["target", "number"]], ret: "number[]", cmp: "unordered",
    cases: [[[2, 7, 11, 15], 9], [[3, 2, 4], 6], [[3, 3], 6]],
    hidden: [[[-1, -2, -3, -4, -5], -8], [[0, 4, 3, 0], 0], [[1, 5, 9, 13, 2], 15],
      { label: "100,000 numbers (needs O(n))", gen: "() => { const n = 100000; const a = Array.from({ length: n }, (_, i) => i * 2); a[n - 1] = 1; return [a, 1 + a[n - 2]]; }" }] },
  "contains-duplicate": { fn: "containsDuplicate", params: [["nums", "number[]"]], ret: "boolean",
    cases: [[[1, 2, 3, 1]], [[1, 2, 3, 4]], [[1, 1, 1, 3, 3, 4, 3, 2, 4, 2]]],
    hidden: [[[5]], [[-1, -1]], [[0, 1, 2, 3, 0]], { label: "100,000 distinct numbers", gen: "() => [Array.from({ length: 100000 }, (_, i) => i * 7 - 3)]" }] },
  "best-time-stock": { fn: "maxProfit", params: [["prices", "number[]"]], ret: "number",
    cases: [[[7, 1, 5, 3, 6, 4]], [[7, 6, 4, 3, 1]]],
    hidden: [[[1]], [[2, 4, 1]], [[3, 3, 5, 0, 0, 3, 1, 4]], { label: "100,000 prices", gen: "() => [Array.from({ length: 100000 }, (_, i) => (i * 7919) % 10007)]" }] },
  "move-zeroes": { fn: "moveZeroes", params: [["nums", "number[]"]], ret: "void", inplace: 0, note: "Modify nums in place. Don't return anything; the judge checks nums after your function runs.",
    cases: [[[0, 1, 0, 3, 12]], [[0]]], hidden: [[[1, 2, 3]], [[0, 0, 1]], [[4, 0, 5, 0, 0, 6]]] },
  "max-subarray": { fn: "maxSubArray", params: [["nums", "number[]"]], ret: "number",
    cases: [[[-2, 1, -3, 4, -1, 2, 1, -5, 4]], [[1]], [[5, 4, -1, 7, 8]]], hidden: [[[-3, -1, -2]], [[-1]], [[2, -1, 2]]] },
  "product-except-self": { fn: "productExceptSelf", params: [["nums", "number[]"]], ret: "number[]",
    cases: [[[1, 2, 3, 4]], [[-1, 1, 0, -3, 3]]], hidden: [[[2, 3]], [[0, 0]], [[1, 1, 1, 1]], [[5, 0, 2]]] },
  "rotate-array": { fn: "rotate", params: [["nums", "number[]"], ["k", "number"]], ret: "void", inplace: 0, note: "Rotate nums in place. The judge checks nums after your function runs.",
    cases: [[[1, 2, 3, 4, 5, 6, 7], 3], [[-1, -100, 3, 99], 2]], hidden: [[[1, 2], 3], [[1], 0], [[1, 2, 3], 3]] },
  "trapping-rain-water": { fn: "trap", params: [["height", "number[]"]], ret: "number",
    cases: [[[0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]], [[4, 2, 0, 3, 2, 5]]], hidden: [[[1]], [[5, 4, 3, 2, 1]], [[2, 0, 2]], [[5, 2, 1, 2, 1, 5]]] },
  "valid-palindrome": { fn: "isPalindrome", params: [["s", "string"]], ret: "boolean",
    cases: [["A man, a plan, a canal: Panama"], ["race a car"], [" "]], hidden: [["0P"], ["ab_a"], ["Madam"], ["a."]] },
  "valid-anagram": { fn: "isAnagram", params: [["s", "string"], ["t", "string"]], ret: "boolean",
    cases: [["anagram", "nagaram"], ["rat", "car"]], hidden: [["a", "ab"], ["", ""], ["aacc", "ccac"], ["listen", "silent"]] },
  "longest-substring": { fn: "lengthOfLongestSubstring", params: [["s", "string"]], ret: "number",
    cases: [["abcabcbb"], ["bbbbb"], ["pwwkew"]], hidden: [[""], [" "], ["dvdf"], ["abba"], ["tmmzuxt"]] },
  "group-anagrams": { fn: "groupAnagrams", params: [["strs", "string[]"]], ret: "string[][]", cmp: "groups",
    cases: [[["eat", "tea", "tan", "ate", "nat", "bat"]], [[""]], [["a"]]], hidden: [[["abc", "bca", "cab", "xyz", "zyx", "q"]], [["", ""]]] },
  "top-k-frequent": { fn: "topKFrequent", params: [["nums", "number[]"], ["k", "number"]], ret: "number[]", cmp: "unordered",
    cases: [[[1, 1, 1, 2, 2, 3], 2], [[1], 1]], hidden: [[[4, 4, 4, 5, 5, 6, 6, 6, 6], 2], [[-1, -1, 2], 1], [[1, 2], 2]] },
  "subarray-sum-k": { fn: "subarraySum", params: [["nums", "number[]"], ["k", "number"]], ret: "number",
    cases: [[[1, 1, 1], 2], [[1, 2, 3], 3]], hidden: [[[1, -1, 0], 0], [[1], 0], [[3, 4, 7, 2, -3, 1, 4, 2], 7], { label: "100,000 numbers (needs O(n))", gen: "() => [Array(100000).fill(1), 10]" }] },
  "longest-consecutive": { fn: "longestConsecutive", params: [["nums", "number[]"]], ret: "number",
    cases: [[[100, 4, 200, 1, 3, 2]], [[0, 3, 7, 2, 5, 8, 4, 6, 0, 1]]], hidden: [[[]], [[1, 2, 0, 1]], [[9, 1, 4, 7, 3, -1, 0, 5, 8, -1, 6]]] },
  "container-water": { fn: "maxArea", params: [["height", "number[]"]], ret: "number",
    cases: [[[1, 8, 6, 2, 5, 4, 8, 3, 7]], [[1, 1]]], hidden: [[[4, 3, 2, 1, 4]], [[1, 2, 1]], { label: "100,000 lines (needs O(n))", gen: "() => [Array.from({ length: 100000 }, (_, i) => (i * 31) % 1000 + 1)]" }] },
  "three-sum": { fn: "threeSum", params: [["nums", "number[]"]], ret: "number[][]", cmp: "groups",
    cases: [[[-1, 0, 1, 2, -1, -4]], [[0, 1, 1]], [[0, 0, 0]]], hidden: [[[-2, 0, 1, 1, 2]], [[0, 0, 0, 0]], [[-4, -2, -2, -2, 0, 1, 2, 2, 2, 3, 3, 4, 4, 6, 6]]] },
  "max-avg-subarray": { fn: "findMaxAverage", params: [["nums", "number[]"], ["k", "number"]], ret: "number", cmp: "float",
    cases: [[[1, 12, -5, -6, 50, 3], 4], [[5], 1]], hidden: [[[0, 4, 0, 3, 2], 1], [[-1], 1], [[4, 0, 4, 3, 3], 5]] },
  "min-window-substring": { fn: "minWindow", params: [["s", "string"], ["t", "string"]], ret: "string",
    cases: [["ADOBECODEBANC", "ABC"], ["a", "a"], ["a", "aa"]], hidden: [["ab", "b"], ["aaflslflsldkalskaaa", "aaa"], ["cabwefgewcwaefgcf", "cae"]] },
  "binary-search": { fn: "search", params: [["nums", "number[]"], ["target", "number"]], ret: "number",
    cases: [[[-1, 0, 3, 5, 9, 12], 9], [[-1, 0, 3, 5, 9, 12], 2]], hidden: [[[5], 5], [[2, 5], 0], [[1, 3, 5, 7, 9, 11], 11], [[1, 3, 5, 7, 9, 11], 1]] },
  "search-insert": { fn: "searchInsert", params: [["nums", "number[]"], ["target", "number"]], ret: "number",
    cases: [[[1, 3, 5, 6], 5], [[1, 3, 5, 6], 2], [[1, 3, 5, 6], 7]], hidden: [[[1, 3, 5, 6], 0], [[1], 1], [[1, 3], 2]] },
  "search-rotated": { fn: "search", params: [["nums", "number[]"], ["target", "number"]], ret: "number",
    cases: [[[4, 5, 6, 7, 0, 1, 2], 0], [[4, 5, 6, 7, 0, 1, 2], 3], [[1], 0]], hidden: [[[3, 1], 1], [[5, 1, 3], 5], [[6, 7, 1, 2, 3, 4, 5], 6], [[1, 3], 3]] },
  "koko-bananas": { fn: "minEatingSpeed", params: [["piles", "number[]"], ["h", "number"]], ret: "number",
    cases: [[[3, 6, 7, 11], 8], [[30, 11, 23, 4, 20], 5], [[30, 11, 23, 4, 20], 6]], hidden: [[[312884470], 312884469], [[1, 1, 1, 1], 4], [[1000000000], 2]] },
  "reverse-list": { fn: "reverseList", params: [["head", "ListNode"]], ret: "ListNode",
    cases: [[[1, 2, 3, 4, 5]], [[1, 2]], [[]]], hidden: [[[7]], [[3, 3, 1]]] },
  "merge-sorted-lists": { fn: "mergeTwoLists", ref: "merge", params: [["list1", "ListNode"], ["list2", "ListNode"]], ret: "ListNode",
    cases: [[[1, 2, 4], [1, 3, 4]], [[], []], [[], [0]]], hidden: [[[5], [1, 2, 4]], [[-3, 0, 9], [-3, 2]]] },
  "linked-list-cycle": { fn: "hasCycle", params: [["head", "cycle"]], ret: "boolean", note: "pos is where the tail connects back to (-1 = no cycle). pos is not passed to your function; you only get head.",
    cases: [[[[3, 2, 0, -4], 1]], [[[1, 2], 0]], [[[1], -1]]], hidden: [[[[], -1]], [[[1, 2, 3, 4], -1]], [[[1, 2, 3, 4], 3]], [[[1], 0]]] },
  "remove-nth": { fn: "removeNthFromEnd", params: [["head", "ListNode"], ["n", "number"]], ret: "ListNode",
    cases: [[[1, 2, 3, 4, 5], 2], [[1], 1], [[1, 2], 1]], hidden: [[[1, 2], 2], [[1, 2, 3], 3]] },
  "valid-parentheses": { fn: "isValid", params: [["s", "string"]], ret: "boolean",
    cases: [["()"], ["()[]{}"], ["(]"]], hidden: [["([)]"], ["{[]}"], ["("], ["]"], ["(("]] },
  "min-stack": { fn: "MinStack", design: true, params: [["operations", "string[]"], ["arguments", "number[][]"]], ret: "any[]", note: "Design problem: the judge creates your class and calls the operations in order. Output lists each call's return value (null for calls that return nothing).",
    cases: [[["MinStack", "push", "push", "push", "getMin", "pop", "top", "getMin"], [[], [-2], [0], [-3], [], [], [], []]]],
    hidden: [[["MinStack", "push", "push", "getMin", "push", "getMin", "pop", "getMin"], [[], [5], [3], [], [7], [], [], []]], [["MinStack", "push", "push", "push", "getMin", "pop", "getMin"], [[], [0], [1], [0], [], [], []]]] },
  "daily-temperatures": { fn: "dailyTemperatures", params: [["temperatures", "number[]"]], ret: "number[]",
    cases: [[[73, 74, 75, 71, 69, 72, 76, 73]], [[30, 40, 50, 60]], [[30, 60, 90]]], hidden: [[[90, 80, 70]], [[55, 38, 53, 81, 61, 93, 97, 32, 43, 78]], { label: "100,000 falling temperatures (needs O(n))", gen: "() => [Array.from({ length: 100000 }, (_, i) => 100000 - i)]" }] },
  "eval-rpn": { fn: "evalRPN", params: [["tokens", "string[]"]], ret: "number",
    cases: [[["2", "1", "+", "3", "*"]], [["4", "13", "5", "/", "+"]], [["10", "6", "9", "3", "+", "-11", "*", "/", "*", "17", "+", "5", "+"]]], hidden: [[["18"]], [["4", "-2", "/"]], [["3", "-4", "+"]]] },
  "level-order": { fn: "levelOrder", params: [["root", "TreeNode"]], ret: "number[][]",
    cases: [[[3, 9, 20, null, null, 15, 7]], [[1]], [[]]], hidden: [[[1, 2, 3, 4, null, null, 5]]] },
  "rotting-oranges": { fn: "orangesRotting", params: [["grid", "number[][]"]], ret: "number",
    cases: [[[[2, 1, 1], [1, 1, 0], [0, 1, 1]]], [[[2, 1, 1], [0, 1, 1], [1, 0, 1]]], [[[0, 2]]]], hidden: [[[[1]]], [[[2, 2], [1, 1], [0, 0], [2, 0]]], [[[0]]]] },
  "number-of-islands": { fn: "numIslands", params: [["grid", "character[][]"]], ret: "number",
    cases: [[[["1", "1", "1", "1", "0"], ["1", "1", "0", "1", "0"], ["1", "1", "0", "0", "0"], ["0", "0", "0", "0", "0"]]], [[["1", "1", "0", "0", "0"], ["1", "1", "0", "0", "0"], ["0", "0", "1", "0", "0"], ["0", "0", "0", "1", "1"]]]],
    hidden: [[[["0"]]], [[["1", "0", "1"], ["0", "1", "0"], ["1", "0", "1"]]]] },
  "fibonacci": { fn: "fib", params: [["n", "number"]], ret: "number", cases: [[2], [3], [4]], hidden: [[0], [1], [30]] },
  "climbing-stairs": { fn: "climbStairs", params: [["n", "number"]], ret: "number", cases: [[2], [3]], hidden: [[1], [10], [45]] },
  "power-of-two": { fn: "isPowerOfTwo", ref: "isPow2Bit", params: [["n", "number"]], ret: "boolean", cases: [[1], [16], [3]], hidden: [[0], [-16], [1073741824], [6]] },
  "subsets": { fn: "subsets", params: [["nums", "number[]"]], ret: "number[][]", cmp: "groups", cases: [[[1, 2, 3]], [[0]]], hidden: [[[4, 1]], [[1, 2, 3, 4]]] },
  "permutations": { fn: "permute", params: [["nums", "number[]"]], ret: "number[][]", cmp: "outer", cases: [[[1, 2, 3]], [[0, 1]], [[1]]], hidden: [[[5, 4, 6, 2]]] },
  "max-depth": { fn: "maxDepth", params: [["root", "TreeNode"]], ret: "number", cases: [[[3, 9, 20, null, null, 15, 7]], [[1, null, 2]]], hidden: [[[]], [[1, 2, 3, 4, null, null, 5, 6]]] },
  "invert-tree": { fn: "invertTree", ref: "invert", params: [["root", "TreeNode"]], ret: "TreeNode", cases: [[[4, 2, 7, 1, 3, 6, 9]], [[2, 1, 3]], [[]]], hidden: [[[1, 2]], [[1, 2, 3, 4, 5]]] },
  "same-tree": { fn: "isSameTree", ref: "isSame", params: [["p", "TreeNode"], ["q", "TreeNode"]], ret: "boolean", cases: [[[1, 2, 3], [1, 2, 3]], [[1, 2], [1, null, 2]], [[1, 2, 1], [1, 1, 2]]], hidden: [[[], []], [[1], []], [[1, 2, 3, 4], [1, 2, 3, 4]]] },
  "validate-bst": { fn: "isValidBST", params: [["root", "TreeNode"]], ret: "boolean", cases: [[[2, 1, 3]], [[5, 1, 4, null, null, 3, 6]]], hidden: [[[5, 4, 6, null, null, 3, 7]], [[1, 1]], [[2147483647]], [[]], [[10, 5, 15, null, null, 6, 20]]] },
  "lca-bst": { fn: "lowestCommonAncestor", ref: "lca", params: [["root", "TreeNode"], ["p", "number"], ["q", "number"]], ret: "number", note: "Simplified: p and q are given as values, and you return the ancestor's value.",
    cases: [[[6, 2, 8, 0, 4, 7, 9, null, null, 3, 5], 2, 8], [[6, 2, 8, 0, 4, 7, 9, null, null, 3, 5], 2, 4], [[2, 1], 2, 1]], hidden: [[[6, 2, 8, 0, 4, 7, 9, null, null, 3, 5], 3, 5], [[6, 2, 8, 0, 4, 7, 9, null, null, 3, 5], 7, 9], [[6, 2, 8, 0, 4, 7, 9, null, null, 3, 5], 0, 5]] },
  "merge-intervals": { fn: "merge", params: [["intervals", "number[][]"]], ret: "number[][]",
    cases: [[[[1, 3], [2, 6], [8, 10], [15, 18]]], [[[1, 4], [4, 5]]]], hidden: [[[[1, 4], [0, 4]]], [[[1, 4], [2, 3]]], [[[2, 3], [4, 5], [6, 7], [8, 9], [1, 10]]]] },
  "kth-largest": { fn: "findKthLargest", params: [["nums", "number[]"], ["k", "number"]], ret: "number",
    cases: [[[3, 2, 1, 5, 6, 4], 2], [[3, 2, 3, 1, 2, 4, 5, 5, 6], 4]], hidden: [[[1], 1], [[2, 1], 2], [[7, 7, 7, 7], 2], [[-1, 2, 0], 3]] },
  "single-number": { fn: "singleNumber", params: [["nums", "number[]"]], ret: "number", cases: [[[2, 2, 1]], [[4, 1, 2, 1, 2]], [[1]]], hidden: [[[-1, -1, -2]], [[0, 5, 5]]] },
  "house-robber": { fn: "rob", params: [["nums", "number[]"]], ret: "number", cases: [[[1, 2, 3, 1]], [[2, 7, 9, 3, 1]]], hidden: [[[0]], [[2, 1, 1, 2]], [[1, 3, 1, 3, 100]]] },
  "coin-change": { fn: "coinChange", params: [["coins", "number[]"], ["amount", "number"]], ret: "number", cases: [[[1, 2, 5], 11], [[2], 3], [[1], 0]], hidden: [[[1, 3, 4], 6], [[186, 419, 83, 408], 6249], [[2, 5, 10, 1], 27]] }
};

